app:
  host: "0.0.0.0"
  port: 7788
  graceful_timeout: 10
  read_timeout: 5
  write_timeout: 10
  stage: development

token:
  secret: someF4k353cR3T!
  issuer: authapp-http

gateway:
  url: https://stein.efishery.com/v1/storages/5e1edf521073e315924ceab4/list

currency:
  url: https://free.currconv.com/api/v7/convert
  api_key: 