version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: authapp:latest
    ports:
      - "5000:5000"
    env_file:
      - .env.example
    volumes:
      - ./:/app
    working_dir: /app
    command: gunicorn -w 2 wsgi:app -b :5000 -t 120
